services:
  postgres:
    image: postgres:17.4
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${PGUSER} # default: postgres
      POSTGRES_PASSWORD: ${PGPASSWORD}
      PGPORT: ${PGPORT}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "${PGPORT}:${PGPORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
