services:
  postgres:
    image: postgres:17.6
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${PGUSER} # default: postgres
      POSTGRES_PASSWORD: ${PGPASSWORD}
      PGPORT: ${PGPORT}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "${PGPORT}:${PGPORT}"
    ## Deliberately choose temporary storage.
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

# volumes:
#   postgres-data:
