services:
  postgres:
    image: postgres:17.4
    shm_size: 128mb
    environment:
      # POSTGRES_USER: devuser # default: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
